server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location = / {
        return 302 /simulator/;
    }

    location /simulator/ {
        try_files $uri $uri/ /simulator/index.html;
    }
}
