import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { convertLetterSidc2NumberSidc } from '@orbat-mapper/convert-symbology'
import symbols2525c from '../src/modules/tactical-symbol-map/symbology/2525c.json'
import symbolsSkkm from '../src/modules/tactical-symbol-map/symbology/skkm.json'
import { app6d } from '../src/symbology/standards/app6d'

const translationsByCode = new Map<string, string>()
for (const symbolSet of Object.values(app6d)) {
  for (const item of symbolSet.mainIcon) {
    const label = item.entitySubtype || item.entityType || item.entity
    if (label) translationsByCode.set(`${symbolSet.symbolSet}:${item.code}`, label)
  }
}

const translations = new Map<string, string>()
const conflicts = new Map<string, Set<string>>()
let converted = 0
let matched = 0

for (const descriptor of [...symbols2525c, ...symbolsSkkm]) {
  const sourceLabel = descriptor.hierarchy.at(-1)
  if (!sourceLabel) continue

  try {
    const result = convertLetterSidc2NumberSidc(descriptor.sidc)
    if (!result.success) continue
    converted++

    const sidc = result.sidc
    const key = `${sidc.slice(4, 6)}:${sidc.slice(10, 16)}`
    const translatedLabel = translationsByCode.get(key)
    if (!translatedLabel) continue
    matched++

    // A legacy multi-word concept can collapse to a generic D-standard leaf
    // such as "circular" or "air". That is not a usable title on its own;
    // leave those cases to the reviewed phrase and tactical-term dictionaries.
    const sourceWordCount = sourceLabel.trim().split(/\s+/).length
    const translatedWordCount = translatedLabel.trim().split(/\s+/).length
    if (sourceWordCount > 1 && translatedWordCount === 1) continue

    const previous = translations.get(sourceLabel)
    if (previous && previous !== translatedLabel) {
      const values = conflicts.get(sourceLabel) || new Set([previous])
      values.add(translatedLabel)
      conflicts.set(sourceLabel, values)
      continue
    }
    translations.set(sourceLabel, translatedLabel)
  } catch {
    // Some legacy weather and national-extension codes have no D-standard SIDC.
  }
}

const sortedTranslations = Object.fromEntries(
  [...translations.entries()].sort(([a], [b]) => a.localeCompare(b, 'en'))
)
const banner = `// This file is generated by scripts/generate-legacy-tactical-labels.mts.\n` +
  `// It maps legacy MIL-STD-2525C/SKKM labels to the Persian APP-6D label\n` +
  `// with the same converted symbol identification code. Do not edit by hand.\n\n`
const output = `${banner}export const generatedLegacyTacticalLabels = ${JSON.stringify(sortedTranslations, null, 2)}\n`
const scriptDirectory = path.dirname(fileURLToPath(import.meta.url))
const outputPath = path.resolve(
  scriptDirectory,
  '../src/modules/tactical-symbol-map/generatedLegacyTacticalLabels.js'
)
await fs.writeFile(outputPath, output, 'utf8')

console.log(JSON.stringify({
  descriptors: symbols2525c.length + symbolsSkkm.length,
  converted,
  matched,
  uniqueTranslations: translations.size,
  conflicts: Object.fromEntries(
    [...conflicts].map(([label, values]) => [label, [...values]])
  )
}, null, 2))
