"""add_offline_maps_table

Revision ID: 0003_add_offline_maps_table
Revises: 0002_add_users_and_scenario_content
Create Date: 2025-01-08 10:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003_add_offline_maps_table'
down_revision = '0002_add_users_and_scenario_content'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offline_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_maps_id'), 'offline_maps', ['id'], unique=False)
    op.create_index(op.f('ix_offline_maps_name'), 'offline_maps', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offline_maps_name'), table_name='offline_maps')
    op.drop_index(op.f('ix_offline_maps_id'), table_name='offline_maps')
    op.drop_table('offline_maps')
    # ### end Alembic commands ###
